config/routes.rb
Rails.application.routes.draw do
  devise_for :users,skip:[:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#new_guest'
  end
  devise_for :admin,skip:[:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  scope module: :public do
    root to: "homes#top"
    get 'about' => 'homes#about'
    get 'users/impressions/index/:user_id' => 'users#index', as: 'users_impressions_index'
    get 'users/favorites/:user_id' => 'users#favorites', as: 'users_favorites'

    get 'users/confirm' => 'users#confirm'
    patch 'users/withdrawal' => 'users#withdrawal'
    resources :users, only: [:show, :edit, :update] do
      resources :reports, only: [:new, :create]
      resources :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
      end
    get '/search' => 'searches#search'
    resources :impressions, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      end
    resources :notifications, only:[:index]
  end
  namespace :admin do
    root to: "homes#top"
    get '/search' => 'searches#search'
    resources :impressions, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
      end
    patch 'users/withdrawal/:user_id' => 'users#withdrawal', as: 'users_withdrawal'
    resources :reports, only: [:index, :show, :update]
    resources :users, only: [:index, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/impression.rb
class Impression < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :notifications, dependent: :destroy

  validates :title, presence: true, length: {maximum: 30}
  validates :body, presence: true, length: {maximum: 5000}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @impression = Impression.where("title LIkE?", "#{word}")
    elsif search == "forward_match"
      @impression = Impression.where("title LikE?", "#{word}%")
    elsif search == "backward_match"
      @impression = Impression.where("title LIKE?", "%#{word}")
    elsif search == "pertial_match"
      @impression = Impression.where("title LIKE?", "%#{word}%")
    else
      @impression = Impression.all
    end
  end

  def create_notification_favorite!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and impression_id = ? and action = ?", current_user.id, user_id, id, "favorite"])
    return if temp.present?
      notification = current_user.active_notifications.new(
        impression_id: id,
        visited_id: user_id,
        action: "favorite"
        )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
  end

  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.select(:user_id).where(impression_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id["user_id"])
    end
    save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    notification = current_user.active_notifications.new(
      impression_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: "comment"
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
  end
end

app/controllers/admin/impressions_controller.rb
class Admin::ImpressionsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @impressions = Impression.all
    @impressions = Impression.order(created_at: :desc)
  end

  def show
    @impression = Impression.find(params[:id])
  end

  def destroy
    impression = Impression.find(params[:id])
    impression.destroy
    redirect_to admin_impressions_path
  end

  private
  def impression_params
    params.require(:impression).permit(:title, :body)
  end
end

app/views/admin/impressions/index.html.erb
<div class="container">
<h3>投稿一覧</h3>
<table class="table">
  <tr>
    <th>タイトル</th>
    <th>投稿者</th>
    <th>投稿日</th>
  </tr>
  <% @impressions.each do |impression| %>
  <tr>
    <td><%= link_to admin_impression_path(impression.id) do %><%= impression.title %><% end %></td>
    <td><%= impression.user.name %></td>
    <td><%= l impression.created_at %></td>
  </tr>
  <% end %>
</table>

app/views/admin/impressions/show.html.erb
<div class="container">
<h4>タイトル：<%= @impression.title %> 投稿者：<%= @impression.user.name %></h4>
<div><%= @impression.body %></div>
<div>投稿日：<%= l @impression.created_at %></div>
<div>作成日：<%= l @impression.updated_at %></div>
<div><%= link_to "削除", admin_impression_path(@impression), method: :delete, data: {confirm: "管理者権限により削除しますか？"}%></div>

<h5>コメント一覧</h5>
<% if @impression.comments.empty? %>
<div>まだコメントはありません</div>
<% else %>
<div><% @impression.comments.each do |comment| %>
<div><%= comment.user.name %>：<%= comment.comment %></div>
<%= link_to "削除", admin_impression_comment_path(comment.impression, comment), method: :delete, data: {confirm: "管理者権限により削除しますか？"} %>
<% end %>
<% end %>
</div>
</div>