config/routes.rb
Rails.application.routes.draw do
  devise_for :users,skip:[:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#new_guest'
  end
  devise_for :admin,skip:[:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  scope module: :public do
    root to: "homes#top"
    get 'about' => 'homes#about'
    get 'users/impressions/index/:user_id' => 'users#index', as: 'users_impressions_index'
    get 'users/favorites/:user_id' => 'users#favorites', as: 'users_favorites'

    get 'users/confirm' => 'users#confirm'
    patch 'users/withdrawal' => 'users#withdrawal'
    resources :users, only: [:show, :edit, :update] do
      resources :reports, only: [:new, :create]
      resources :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
      end
    get '/search' => 'searches#search'
    resources :impressions, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      end
    resources :notifications, only:[:index]
  end
  namespace :admin do
    root to: "homes#top"
    get '/search' => 'searches#search'
    resources :impressions, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
      end
    patch 'users/withdrawal/:user_id' => 'users#withdrawal', as: 'users_withdrawal'
    resources :reports, only: [:index, :show, :update]
    resources :users, only: [:index, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :reporter, class_name: "User"
  belongs_to :reported, class_name: "User"

  enum status: { waiting: 0, keep: 1, finish: 2 }
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @reports = Report.all
    @reports = Report.order(created_at: :desc)
  end

  def show
    @report = Report.find(params[:id])
  end

  def update
    @report = Report.find(params[:id])
    if @report.update(report_params)
      redirect_to request.referer
      flash[:notice] = "対応ステータスを更新しました"
    end
  end

  private
  def report_params
    params.require(:report).permit(:status)
  end
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/views/admin/reports/index.html.erb
<div class="container">
<%= flash[:notice] %>
<table class="table">
<tr>
<th>通報ID</th>
<th>問題の会員</th>
<th>通報者</th>
<th>ステータス</th>
</tr>
<% @reports.each do |report| %>
<tr>
<td><%= link_to admin_report_path(report.id) do %><%= report.id %><% end %></td>
<td><%= report.reported.name %></td>
<td><%= report.reporter.name %></td>
<td><%= report.status_i18n %></td>
</tr>
<% end %>
</table>
</div>

app/views/admin/reports/show.html.erb
<div class="container">
<%= flash[:notice] %>
<h3>通報詳細</h3>
<div>通報ID：<%= @report.id %></div>
<div>問題の会員：<%= link_to admin_user_path(@report.reported_id) do %><%= @report.reported.name %><% end %></div>
<div>理由：<%= @report.reason %></div>
<div>通報者：<%= @report.reporter.name %></div>
<div>対応ステータス：
<%= @report.status_i18n %>
<%= form_with model: @report, url: admin_report_path(@report), method: :patch, local: true do |f| %>
<%= f.select :status, Report.statuses.keys.map { |k| [t("enums.report.status.#{k}"), k] } %>
<%= f.submit "更新" %>
<% end %></div>
</div>