config/routes.rb
Rails.application.routes.draw do
  devise_for :users,skip:[:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#new_guest'
  end
  devise_for :admin,skip:[:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  scope module: :public do
    root to: "homes#top"
    get 'about' => 'homes#about'
    get 'users/impressions/index/:user_id' => 'users#index', as: 'users_impressions_index'
    get 'users/favorites/:user_id' => 'users#favorites', as: 'users_favorites'

    get 'users/confirm' => 'users#confirm'
    patch 'users/withdrawal' => 'users#withdrawal'
    resources :users, only: [:show, :edit, :update] do
      resources :reports, only: [:new, :create]
      resources :relationships, only: [:create, :destroy]
        get 'followings' => 'relationships#followings', as: 'followings'
        get 'followers' => 'relationships#followers', as: 'followers'
      end
    get '/search' => 'searches#search'
    resources :impressions, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
      end
    resources :notifications, only:[:index]
  end
  namespace :admin do
    root to: "homes#top"
    get '/search' => 'searches#search'
    resources :impressions, only: [:index, :show, :destroy] do
      resources :comments, only: [:destroy]
      end
    patch 'users/withdrawal/:user_id' => 'users#withdrawal', as: 'users_withdrawal'
    resources :reports, only: [:index, :show, :update]
    resources :users, only: [:index, :show]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PFKokontozaiGameIApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="pt-3 pb-3">
      <% if admin_signed_in? %>
      <div class="container">
      <h4><%= link_to "古今東西ゲーム愛好会", admin_root_path %></h4>
      <%= link_to "会員一覧", admin_users_path %>
      <%= link_to "全体投稿一覧", admin_impressions_path %>
      <%= link_to "通報", admin_reports_path %>
      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
      <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['ユーザー','User'],['投稿','Impression']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"],["前方一致","forward_match"],["後方一致","backward_match"],["部分一致","partial_match"]]) %>
      <%= f.submit "検索" %>
      <% end %>
      </div>
      <% elsif user_signed_in? %>
      <div class="container">
      <h4><%= link_to "古今東西ゲーム愛好会", root_path %></h4>
      <%= link_to "ユーザーページ", user_path(current_user.id) %>
      <%= link_to "全体投稿一覧", impressions_path %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['ユーザー','User'],['投稿','Impression']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"],["前方一致","forward_match"],["後方一致","backward_match"],["部分一致","partial_match"]]) %>
      <%= f.submit "検索" %>
      <% end %>
      </div>
      <% else %>
      <div class="container">
      <h4><%= link_to "古今東西ゲーム愛好会", root_path %></h4>
      <%= link_to "新規登録", new_user_registration_path %>
      <%= link_to "ログイン", new_user_session_path %>
      <%= link_to "全体投稿一覧", impressions_path %>
      <% end %>
      </div>
    </header>
    <main><%= yield %></main>
    <footer></footer>
  </body>
</html>